In [1]:
import requests

In [2]:
response = requests.get("https://api.github.com")

In [3]:
response.status_code

200

In [4]:
response.json()

{'current_user_url': 'https://api.github.com/user',
 'current_user_authorizations_html_url': 'https://github.com/settings/connections/applications{/client_id}',
 'authorizations_url': 'https://api.github.com/authorizations',
 'code_search_url': 'https://api.github.com/search/code?q={query}{&page,per_page,sort,order}',
 'commit_search_url': 'https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}',
 'emails_url': 'https://api.github.com/user/emails',
 'emojis_url': 'https://api.github.com/emojis',
 'events_url': 'https://api.github.com/events',
 'feeds_url': 'https://api.github.com/feeds',
 'followers_url': 'https://api.github.com/user/followers',
 'following_url': 'https://api.github.com/user/following{/target}',
 'gists_url': 'https://api.github.com/gists{/gist_id}',
 'hub_url': 'https://api.github.com/hub',
 'issue_search_url': 'https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}',
 'issues_url': 'https://api.github.com/issues',
 'keys_url': 'https://api.github.com/user/keys',
 'label_search_url': 'https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}',
 'notifications_url': 'https://api.github.com/notifications',
 'organization_url': 'https://api.github.com/orgs/{org}',
 'organization_repositories_url': 'https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}',
 'organization_teams_url': 'https://api.github.com/orgs/{org}/teams',
 'public_gists_url': 'https://api.github.com/gists/public',
 'rate_limit_url': 'https://api.github.com/rate_limit',
 'repository_url': 'https://api.github.com/repos/{owner}/{repo}',
 'repository_search_url': 'https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}',
 'current_user_repositories_url': 'https://api.github.com/user/repos{?type,page,per_page,sort}',
 'starred_url': 'https://api.github.com/user/starred{/owner}{/repo}',
 'starred_gists_url': 'https://api.github.com/gists/starred',
 'topic_search_url': 'https://api.github.com/search/topics?q={query}{&page,per_page}',
 'user_url': 'https://api.github.com/users/{user}',
 'user_organizations_url': 'https://api.github.com/user/orgs',
 'user_repositories_url': 'https://api.github.com/users/{user}/repos{?type,page,per_page,sort}',
 'user_search_url': 'https://api.github.com/search/users?q={query}{&page,per_page,sort,order}'}

In [5]:
url = "https://export.arxiv.org/api/query?search_query=nlp&start=0&max_results=100"

In [6]:
response = requests.get(url)

In [7]:
response.status_code

200

In [8]:
response.text

'<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<feed xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:arxiv="http://arxiv.org/schemas/atom" xmlns="http://www.w3.org/2005/Atom">\n  <id>https://arxiv.org/api/bZsEoc+BiYqeYP1tPzRMBG0qFEY</id>\n  <title>arXiv Query: search_query=all:nlp&amp;id_list=&amp;start=0&amp;max_results=100</title>\n  <updated>2026-07-26T11:02:38Z</updated>\n  <link href="https://arxiv.org/api/query?search_query=all:nlp&amp;start=0&amp;max_results=100&amp;id_list=" type="application/atom+xml"/>\n  <opensearch:itemsPerPage>100</opensearch:itemsPerPage>\n  <opensearch:totalResults>13540</opensearch:totalResults>\n  <opensearch:startIndex>0</opensearch:startIndex>\n  <entry>\n    <id>http://arxiv.org/abs/2104.12405v2</id>\n    <title>A dissemination workshop for introducing young Italian students to NLP</title>\n    <updated>2021-05-14T07:59:50Z</updated>\n    <link href="https://arxiv.org/abs/2104.12405v2" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2104.12405v2" rel="related" type="application/pdf" title="pdf"/>\n    <summary>We describe and make available the game-based material developed for a laboratory run at several Italian science festivals to popularize NLP among young students.</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2021-04-26T09:00:56Z</published>\n    <arxiv:comment>3 pages, 4 figures, accepted at Teaching NLP 2021 workshop</arxiv:comment>\n    <arxiv:primary_category term="cs.CL"/>\n    <arxiv:journal_ref>Proceedings of the 5th Workshop on Teaching NLP (2021) 52-54</arxiv:journal_ref>\n    <author>\n      <name>Lucio Messina</name>\n    </author>\n    <author>\n      <name>Lucia Busso</name>\n    </author>\n    <author>\n      <name>Claudia Roberta Combei</name>\n    </author>\n    <author>\n      <name>Ludovica Pannitto</name>\n    </author>\n    <author>\n      <name>Alessio Miaschi</name>\n    </author>\n    <author>\n      <name>Gabriele Sarti</name>\n    </author>\n    <author>\n      <name>Malvina Nissim</name>\n    </author>\n    <arxiv:doi>10.18653/v1/2021.teachingnlp-1.7</arxiv:doi>\n    <link rel="related" href="https://doi.org/10.18653/v1/2021.teachingnlp-1.7" title="doi"/>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2104.12422v2</id>\n    <title>Teaching NLP with Bracelets and Restaurant Menus: An Interactive Workshop for Italian Students</title>\n    <updated>2021-05-14T07:49:21Z</updated>\n    <link href="https://arxiv.org/abs/2104.12422v2" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2104.12422v2" rel="related" type="application/pdf" title="pdf"/>\n    <summary>Although Natural Language Processing (NLP) is at the core of many tools young people use in their everyday life, high school curricula (in Italy) do not include any computational linguistics education. This lack of exposure makes the use of such tools less responsible than it could be and makes choosing computational linguistics as a university degree unlikely. To raise awareness, curiosity, and longer-term interest in young people, we have developed an interactive workshop designed to illustrate the basic principles of NLP and computational linguistics to high school Italian students aged between 13 and 18 years. The workshop takes the form of a game in which participants play the role of machines needing to solve some of the most common problems a computer faces in understanding language: from voice recognition to Markov chains to syntactic parsing. Participants are guided through the workshop with the help of instructors, who present the activities and explain core concepts from computational linguistics. The workshop was presented at numerous outlets in Italy between 2019 and 2021, both face-to-face and online.</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2021-04-26T09:23:52Z</published>\n    <arxiv:comment>11 pages, 16 figures, accepted at Teaching NLP 2021 Workshop</arxiv:comment>\n    <arxiv:primary_category term="cs.CL"/>\n    <arxiv:journal_ref>Proceedings of the 5th Workshop on Teaching NLP (2021) 160-170</arxiv:journal_ref>\n    <author>\n      <name>Ludovica Pannitto</name>\n    </author>\n    <author>\n      <name>Lucia Busso</name>\n    </author>\n    <author>\n      <name>Claudia Roberta Combei</name>\n    </author>\n    <author>\n      <name>Lucio Messina</name>\n    </author>\n    <author>\n      <name>Alessio Miaschi</name>\n    </author>\n    <author>\n      <name>Gabriele Sarti</name>\n    </author>\n    <author>\n      <name>Malvina Nissim</name>\n    </author>\n    <arxiv:doi>10.18653/v1/2021.teachingnlp-1.26</arxiv:doi>\n    <link rel="related" href="https://doi.org/10.18653/v1/2021.teachingnlp-1.26" title="doi"/>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2412.08520v1</id>\n    <title>GR-NLP-TOOLKIT: An Open-Source NLP Toolkit for Modern Greek</title>\n    <updated>2024-12-11T16:34:23Z</updated>\n    <link href="https://arxiv.org/abs/2412.08520v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2412.08520v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>We present GR-NLP-TOOLKIT, an open-source natural language processing (NLP) toolkit developed specifically for modern Greek. The toolkit provides state-of-the-art performance in five core NLP tasks, namely part-of-speech tagging, morphological tagging, dependency parsing, named entity recognition, and Greeklishto-Greek transliteration. The toolkit is based on pre-trained Transformers, it is freely available, and can be easily installed in Python (pip install gr-nlp-toolkit). It is also accessible through a demonstration platform on HuggingFace, along with a publicly available API for non-commercial use. We discuss the functionality provided for each task, the underlying methods, experiments against comparable open-source toolkits, and future possible enhancements. The toolkit is available at: https://github.com/nlpaueb/gr-nlp-toolkit</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>\n    <category term="cs.AI" scheme="http://arxiv.org/schemas/atom"/>\n    <category term="cs.SE" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2024-12-11T16:34:23Z</published>\n    <arxiv:comment>Accepted Demo Paper @ COLING 2025 (Github: https://github.com/nlpaueb/gr-nlp-toolkit/, Demo: https://huggingface.co/spaces/AUEB-NLP/greek-nlp-toolkit-demo, API: https://huggingface.co/spaces/AUEB-NLP/The-Greek-NLP-API)</arxiv:comment>\n    <arxiv:primary_category term="cs.CL"/>\n    <author>\n      <name>Lefteris Loukas</name>\n    </author>\n    <author>\n      <name>Nikolaos Smyrnioudis</name>\n    </author>\n    <author>\n      <name>Chrysa Dikonomaki</name>\n    </author>\n    <author>\n      <name>Spyros Barbakos</name>\n    </author>\n    <author>\n      <name>Anastasios Toumazatos</name>\n    </author>\n    <author>\n      <name>John Koutsikakis</name>\n    </author>\n    <author>\n      <name>Manolis Kyriakakis</name>\n    </author>\n    <author>\n      <name>Mary Georgiou</name>\n    </author>\n    <author>\n      <name>Stavros Vassos</name>\n    </author>\n    <author>\n      <name>John Pavlopoulos</name>\n    </author>\n    <author>\n      <name>Ion Androutsopoulos</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2106.02359v3</id>\n    <title>How Good Is NLP? A Sober Look at NLP Tasks through the Lens of Social Impact</title>\n    <updated>2023-01-18T04:23:03Z</updated>\n    <link href="https://arxiv.org/abs/2106.02359v3" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2106.02359v3" rel="related" type="application/pdf" title="pdf"/>\n    <summary>Recent years have seen many breakthroughs in natural language processing (NLP), transitioning it from a mostly theoretical field to one with many real-world applications. Noting the rising number of applications of other machine learning and AI techniques with pervasive societal impact, we anticipate the rising importance of developing NLP technologies for social good. Inspired by theories in moral philosophy and global priorities research, we aim to promote a guideline for social good in the context of NLP. We lay the foundations via the moral philosophy definition of social good, propose a framework to evaluate the direct and indirect real-world impact of NLP tasks, and adopt the methodology of global priorities research to identify priority causes for NLP research. Finally, we use our theoretical framework to provide some practical guidelines for future NLP research for social good. Our data and code are available at http://github.com/zhijing-jin/nlp4sg_acl2021. In addition, we curate a list of papers and resources on NLP for social good at https://github.com/zhijing-jin/NLP4SocialGood_Papers.</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>\n    <category term="cs.AI" scheme="http://arxiv.org/schemas/atom"/>\n    <category term="cs.CY" scheme="http://arxiv.org/schemas/atom"/>\n    <category term="cs.LG" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2021-06-04T09:17:15Z</published>\n    <arxiv:comment>Findings of ACL 2021; also accepted at the NLP for Positive Impact workshop@ACL 2021</arxiv:comment>\n    <arxiv:primary_category term="cs.CL"/>\n    <author>\n      <name>Zhijing Jin</name>\n    </author>\n    <author>\n      <name>Geeticka Chauhan</name>\n    </author>\n    <author>\n      <name>Brian Tse</name>\n    </author>\n    <author>\n      <name>Mrinmaya Sachan</name>\n    </author>\n    <author>\n      <name>Rada Mihalcea</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2412.04784v2</id>\n    <title>NLP-ADBench: NLP Anomaly Detection Benchmark</title>\n    <updated>2025-10-09T19:13:25Z</updated>\n    <link href="https://arxiv.org/abs/2412.04784v2" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2412.04784v2" rel="related" type="application/pdf" title="pdf"/>\n    <summary>Anomaly detection (AD) is an important machine learning task with applications in fraud detection, content moderation, and user behavior analysis. However, AD is relatively understudied in a natural language processing (NLP) context, limiting its effectiveness in detecting harmful content, phishing attempts, and spam reviews. We introduce NLP-ADBench, the most comprehensive NLP anomaly detection (NLP-AD) benchmark to date, which includes eight curated datasets and 19 state-of-the-art algorithms. These span 3 end-to-end methods and 16 two-step approaches that adapt classical, non-AD methods to language embeddings from BERT and OpenAI. Our empirical results show that no single model dominates across all datasets, indicating a need for automated model selection. Moreover, two-step methods with transformer-based embeddings consistently outperform specialized end-to-end approaches, with OpenAI embeddings outperforming those of BERT. We release NLP-ADBench at https://github.com/USC-FORTIS/NLP-ADBench, providing a unified framework for NLP-AD and supporting future investigations.</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>\n    <category term="cs.LG" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2024-12-06T05:30:41Z</published>\n    <arxiv:comment>EMNLP Findings 2025. The project is available at https://github.com/USC-FORTIS/NLP-ADBench</arxiv:comment>\n    <arxiv:primary_category term="cs.CL"/>\n    <author>\n      <name>Yuangang Li</name>\n    </author>\n    <author>\n      <name>Jiaqi Li</name>\n    </author>\n    <author>\n      <name>Zhuo Xiao</name>\n    </author>\n    <author>\n      <name>Tiankai Yang</name>\n    </author>\n    <author>\n      <name>Yi Nian</name>\n    </author>\n    <author>\n      <name>Xiyang Hu</name>\n    </author>\n    <author>\n      <name>Yue Zhao</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2105.00895v1</id>\n    <title>Teaching NLP outside Linguistics and Computer Science classrooms: Some challenges and some opportunities</title>\n    <updated>2021-05-03T14:30:32Z</updated>\n    <link href="https://arxiv.org/abs/2105.00895v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2105.00895v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>NLP\'s sphere of influence went much beyond computer science research and the development of software applications in the past decade. We see people using NLP methods in a range of academic disciplines from Asian Studies to Clinical Oncology. We also notice the presence of NLP as a module in most of the data science curricula within and outside of regular university setups. These courses are taken by students from very diverse backgrounds. This paper takes a closer look at some issues related to teaching NLP to these diverse audiences based on my classroom experiences, and identifies some challenges the instructors face, particularly when there is no ecosystem of related courses for the students. In this process, it also identifies a few challenge areas for both NLP researchers and tool developers.</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2021-05-03T14:30:32Z</published>\n    <arxiv:comment>To appear in the Teaching NLP workshop at NAACL 2021</arxiv:comment>\n    <arxiv:primary_category term="cs.CL"/>\n    <author>\n      <name>Sowmya Vajjala</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2010.03061v1</id>\n    <title>A Survey on Recognizing Textual Entailment as an NLP Evaluation</title>\n    <updated>2020-10-06T22:23:00Z</updated>\n    <link href="https://arxiv.org/abs/2010.03061v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2010.03061v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>Recognizing Textual Entailment (RTE) was proposed as a unified evaluation framework to compare semantic understanding of different NLP systems. In this survey paper, we provide an overview of different approaches for evaluating and understanding the reasoning capabilities of NLP systems. We then focus our discussion on RTE by highlighting prominent RTE datasets as well as advances in RTE dataset that focus on specific linguistic phenomena that can be used to evaluate NLP systems on a fine-grained level. We conclude by arguing that when evaluating NLP systems, the community should utilize newly introduced RTE datasets that focus on specific linguistic phenomena.</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2020-10-06T22:23:00Z</published>\n    <arxiv:comment>1st Workshop on Evaluation and Comparison for NLP systems (Eval4NLP) at EMNLP 2020; 18 pages</arxiv:comment>\n    <arxiv:primary_category term="cs.CL"/>\n    <author>\n      <name>Adam Poliak</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2408.05664v1</id>\n    <title>Training an NLP Scholar at a Small Liberal Arts College: A Backwards Designed Course Proposal</title>\n    <updated>2024-08-11T00:50:59Z</updated>\n    <link href="https://arxiv.org/abs/2408.05664v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2408.05664v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>The rapid growth in natural language processing (NLP) over the last couple years has generated student interest and excitement in learning more about the field. In this paper, we present two types of students that NLP courses might want to train. First, an "NLP engineer" who is able to flexibly design, build and apply new technologies in NLP for a wide range of tasks. Second, an "NLP scholar" who is able to pose, refine and answer questions in NLP and how it relates to the society, while also learning to effectively communicate these answers to a broader audience. While these two types of skills are not mutually exclusive -- NLP engineers should be able to think critically, and NLP scholars should be able to build systems -- we think that courses can differ in the balance of these skills. As educators at Small Liberal Arts Colleges, the strengths of our students and our institution favors an approach that is better suited to train NLP scholars. In this paper we articulate what kinds of skills an NLP scholar should have, and then adopt a backwards design to propose course components that can aid the acquisition of these skills.</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2024-08-11T00:50:59Z</published>\n    <arxiv:comment>9 pages, Presented at 6th Workshop on Teaching NLP</arxiv:comment>\n    <arxiv:primary_category term="cs.CL"/>\n    <author>\n      <name>Grusha Prasad</name>\n    </author>\n    <author>\n      <name>Forrest Davis</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2204.07288v1</id>\n    <title>Characterizing the Efficiency vs. Accuracy Trade-off for Long-Context NLP Models</title>\n    <updated>2022-04-15T01:52:45Z</updated>\n    <link href="https://arxiv.org/abs/2204.07288v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2204.07288v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>With many real-world applications of Natural Language Processing (NLP) comprising of long texts, there has been a rise in NLP benchmarks that measure the accuracy of models that can handle longer input sequences. However, these benchmarks do not consider the trade-offs between accuracy, speed, and power consumption as input sizes or model sizes are varied. In this work, we perform a systematic study of this accuracy vs. efficiency trade-off on two widely used long-sequence models - Longformer-Encoder-Decoder (LED) and Big Bird - during fine-tuning and inference on four datasets from the SCROLLS benchmark. To study how this trade-off differs across hyperparameter settings, we compare the models across four sequence lengths (1024, 2048, 3072, 4096) and two model sizes (base and large) under a fixed resource budget. We find that LED consistently achieves better accuracy at lower energy costs than Big Bird. For summarization, we find that increasing model size is more energy efficient than increasing sequence length for higher accuracy. However, this comes at the cost of a large drop in inference speed. For question answering, we find that smaller models are both more efficient and more accurate due to the larger training batch sizes possible under a fixed resource budget.</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>\n    <category term="cs.LG" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2022-04-15T01:52:45Z</published>\n    <arxiv:comment>Accepted at NLP Power! Workshop on Efficient Benchmarking in NLP at ACL2022</arxiv:comment>\n    <arxiv:primary_category term="cs.CL"/>\n    <author>\n      <name>Phyllis Ang</name>\n    </author>\n    <author>\n      <name>Bhuwan Dhingra</name>\n    </author>\n    <author>\n      <name>Lisa Wu Wills</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2102.13461v1</id>\n    <title>Methods for the Design and Evaluation of HCI+NLP Systems</title>\n    <updated>2021-02-26T13:37:10Z</updated>\n    <link href="https://arxiv.org/abs/2102.13461v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2102.13461v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>HCI and NLP traditionally focus on different evaluation methods. While HCI involves a small number of people directly and deeply, NLP traditionally relies on standardized benchmark evaluations that involve a larger number of people indirectly. We present five methodological proposals at the intersection of HCI and NLP and situate them in the context of ML-based NLP models. Our goal is to foster in

In [9]:
print(response.text[:1000])

<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:arxiv="http://arxiv.org/schemas/atom" xmlns="http://www.w3.org/2005/Atom">
  <id>https://arxiv.org/api/bZsEoc+BiYqeYP1tPzRMBG0qFEY</id>
  <title>arXiv Query: search_query=all:nlp&amp;id_list=&amp;start=0&amp;max_results=100</title>
  <updated>2026-07-26T11:02:38Z</updated>
  <link href="https://arxiv.org/api/query?search_query=all:nlp&amp;start=0&amp;max_results=100&amp;id_list=" type="application/atom+xml"/>
  <opensearch:itemsPerPage>100</opensearch:itemsPerPage>
  <opensearch:totalResults>13540</opensearch:totalResults>
  <opensearch:startIndex>0</opensearch:startIndex>
  <entry>
    <id>http://arxiv.org/abs/2104.12405v2</id>
    <title>A dissemination workshop for introducing young Italian students to NLP</title>
    <updated>2021-05-14T07:59:50Z</updated>
    <link href="https://arxiv.org/abs/2104.12405v2" rel="alternate" type="text/html"/>
    <link href="https://arxiv.org/p

In [10]:
import xml.etree.ElementTree as ET

In [11]:
root = ET.fromstring(response.text)

In [12]:
root

In [13]:
len(root)

107

In [14]:
entries = root.findall("{http://www.w3.org/2005/Atom}entry")

In [15]:
len(entries)

100

In [16]:
first_article = entries[0]

In [17]:
first_article

In [18]:
for item in first_article:
    print(item.tag)

{http://www.w3.org/2005/Atom}id
{http://www.w3.org/2005/Atom}title
{http://www.w3.org/2005/Atom}updated
{http://www.w3.org/2005/Atom}link
{http://www.w3.org/2005/Atom}link
{http://www.w3.org/2005/Atom}summary
{http://www.w3.org/2005/Atom}category
{http://www.w3.org/2005/Atom}published
{http://arxiv.org/schemas/atom}comment
{http://arxiv.org/schemas/atom}primary_category
{http://arxiv.org/schemas/atom}journal_ref
{http://www.w3.org/2005/Atom}author
{http://www.w3.org/2005/Atom}author
{http://www.w3.org/2005/Atom}author
{http://www.w3.org/2005/Atom}author
{http://www.w3.org/2005/Atom}author
{http://www.w3.org/2005/Atom}author
{http://www.w3.org/2005/Atom}author
{http://arxiv.org/schemas/atom}doi
{http://www.w3.org/2005/Atom}link

In [19]:
title = first_article.find("{http://www.w3.org/2005/Atom}title")

In [20]:
title

In [21]:
title_text = title.text

In [22]:
title_text

'A dissemination workshop for introducing young Italian students to NLP'

In [23]:
for article in entries:
    title = article.find("{http://www.w3.org/2005/Atom}title")
    print(title.text)

A dissemination workshop for introducing young Italian students to NLP
Teaching NLP with Bracelets and Restaurant Menus: An Interactive Workshop for Italian Students
GR-NLP-TOOLKIT: An Open-Source NLP Toolkit for Modern Greek
How Good Is NLP? A Sober Look at NLP Tasks through the Lens of Social Impact
NLP-ADBench: NLP Anomaly Detection Benchmark
Teaching NLP outside Linguistics and Computer Science classrooms: Some challenges and some opportunities
A Survey on Recognizing Textual Entailment as an NLP Evaluation
Training an NLP Scholar at a Small Liberal Arts College: A Backwards Designed Course Proposal
Characterizing the Efficiency vs. Accuracy Trade-off for Long-Context NLP Models
Methods for the Design and Evaluation of HCI+NLP Systems
Natural Language Processing 4 All (NLP4All): A New Online Platform for Teaching and Learning NLP Concepts
Transformers: "The End of History" for NLP?
Defining a New NLP Playground
TurkicNLP: An NLP Toolkit for Turkic Languages
A Survey on Patent Analysis: From NLP to Multimodal AI
Autoencoder-Based Framework to Capture Vocabulary Quality in NLP
Towards Linguistically Generalizable NLP Systems: A Workshop and Shared Task
Wikimedia data for AI: a review of Wikimedia datasets for NLP tasks and AI-assisted editing
From Code-Centric to Concept-Centric: Teaching NLP with LLM-Assisted "Vibe Coding"
Solving the Right Problem is Key for Translational NLP: A Case Study in UMLS Vocabulary Insertion
NLP-assisted software testing: A systematic mapping of the literature
News Signals: An NLP Library for Text and Time Series
Augmenting NLP data to counter Annotation Artifacts for NLI Tasks
What is SemEval evaluating? A Systematic Analysis of Evaluation Campaigns in NLP
Dealing with Data for RE: Mitigating Challenges while using NLP and Generative AI
Applied Language Technology: NLP for the Humanities
Explaining Predictions of Non-Linear Classifiers in NLP
Gradual Fine-Tuning for Low-Resource Domain Adaptation
Complete Complementary Results Report of the MARF's NLP Approach to the DEFT 2010 Competition
Missing Information, Unresponsive Authors, Experimental Flaws: The Impossibility of Assessing the Reproducibility of Previous Human Evaluations in NLP
Neural Unsupervised Domain Adaptation in NLP---A Survey
Evolution of ESG-focused DLT Research: An NLP Analysis of the Literature
Aviation Safety Enhancement via NLP & Deep Learning: Classifying Flight Phases in ATSB Safety Reports
Faithfulness and the Notion of Adversarial Sensitivity in NLP Explanations
Searching for a Search Method: Benchmarking Search Algorithms for Generating NLP Adversarial Examples
Towards Open-Ended Discovery for Low-Resource NLP
Setting Standards in Turkish NLP: TR-MMLU for Large Language Model Evaluation
Aspect-based Sentiment Evaluation of Chess Moves (ASSESS): an NLP-based Method for Evaluating Chess Strategies from Textbooks
Parsing Thai Social Data: A New Challenge for Thai NLP
Does it care what you asked? Understanding Importance of Verbs in Deep Learning QA System
Annotation Imputation to Individualize Predictions: Initial Studies on Distribution Dynamics and Model Predictions
Advancing Uto-Aztecan Language Technologies: A Case Study on the Endangered Comanche Language
The Nature of NLP: Analyzing Contributions in NLP Papers
Explainable Identification of Hate Speech towards Islam using Graph Neural Networks
TajPersLexon: A Tajik-Persian Lexical Resource and Hybrid Model for Cross-Script Low-Resource NLP
NLP Security and Ethics, in the Wild
The NLP Engine: A Universal Turing Machine for NLP
torchdistill Meets Hugging Face Libraries for Reproducible, Coding-Free Deep Learning Studies: A Case Study on NLP
NLP for Ghanaian Languages
The Current State of Finnish NLP
Preregistering NLP Research
State of NLP in Kenya: A Survey
A Survey of Race, Racism, and Anti-Racism in NLP
An NLP Assistant for Clide
The Law and NLP: Bridging Disciplinary Disconnects
CogErgLLM: Exploring Large Language Model Systems Design Perspective Using Cognitive Ergonomics
STAMP 4 NLP -- An Agile Framework for Rapid Quality-Driven NLP Applications Development
Foundations and Evaluations in NLP
NLP needs Diversity outside of 'Diversity'
The Radiation Oncology NLP Database
The NLP Sandbox: an efficient model-to-data system to enable federated and unbiased evaluation of clinical NLP models
Switching Contexts: Transportability Measures for NLP
A Material Lens on Coloniality in NLP
Towards Climate Awareness in NLP Research
Grounding 'Grounding' in NLP
Spark NLP: Natural Language Understanding at Scale
NLP Privacy Risk Identification in Social Media (NLP-PRISM): A Survey
A Data-Centric Framework for Composable NLP Workflows
Visualizing NLP annotations for Crowdsourcing
An Audit on the Perspectives and Challenges of Hallucinations in NLP
TextAttack: Lessons learned in designing Python frameworks for NLP
Large Language Models Meet NLP: A Survey
A Survey of Data Augmentation Approaches for NLP
NLP Sampling: Combining MCMC and NLP Methods for Diverse Constrained Sampling
NLP and CALL: integration is working
On the Origins of Bias in NLP through the Lens of the Jim Code
Low-Resource Adaptation of Neural NLP Models
Distributed NLP
From Insights to Actions: The Impact of Interpretability and Analysis Research on NLP
NLPStatTest: A Toolkit for Comparing NLP System Performance
NusaCrowd: A Call for Open and Reproducible NLP Research in Indonesian Languages
Towards Improving Adversarial Training of NLP Models
NLP for Knowledge Discovery and Information Extraction from Energetics Corpora
Challenges and Strategies in Cross-Cultural NLP
The Future of NLP may not be at NLP Conferences: Scholarly Migration Patterns in Natural Language Processing
A Taxonomy of Ambiguity Types for NLP
Measure and Improve Robustness in NLP Models: A Survey
Energy and Policy Considerations for Deep Learning in NLP
Leveraging AI and NLP for Bank Marketing: A Systematic Review and Gap Analysis
autoNLP: NLP Feature Recommendations for Text Analytics Applications
NLP for The Greek Language: A Longer Survey
Countering Online Hate Speech: An NLP Perspective
Taxonomic survey of Hindi Language NLP systems
Re-contextualizing Fairness in NLP: The Case of India
A Survey of Adversarial Defences and Robustness in NLP
VNLP: Turkish NLP Package
Notes on Deep Learning for NLP
Reproducibility Beyond the Research Community: Experience from NLP Beginners
Distillation-Resistant Watermarking for Model Protection in NLP
Representing Numbers in NLP: a Survey and a Vision

In [24]:
titles = []
for article in entries:
    title = article.find("{http://www.w3.org/2005/Atom}title")
    titles.append(title.text)

In [25]:
titles

['A dissemination workshop for introducing young Italian students to NLP',
 'Teaching NLP with Bracelets and Restaurant Menus: An Interactive Workshop for Italian Students',
 'GR-NLP-TOOLKIT: An Open-Source NLP Toolkit for Modern Greek',
 'How Good Is NLP? A Sober Look at NLP Tasks through the Lens of Social Impact',
 'NLP-ADBench: NLP Anomaly Detection Benchmark',
 'Teaching NLP outside Linguistics and Computer Science classrooms: Some challenges and some opportunities',
 'A Survey on Recognizing Textual Entailment as an NLP Evaluation',
 'Training an NLP Scholar at a Small Liberal Arts College: A Backwards Designed Course Proposal',
 'Characterizing the Efficiency vs. Accuracy Trade-off for Long-Context NLP Models',
 'Methods for the Design and Evaluation of HCI+NLP Systems',
 'Natural Language Processing 4 All (NLP4All): A New Online Platform for Teaching and Learning NLP Concepts',
 'Transformers: "The End of History" for NLP?',
 'Defining a New NLP Playground',
 'TurkicNLP: An NLP Toolkit for Turkic Languages',
 'A Survey on Patent Analysis: From NLP to Multimodal AI',
 'Autoencoder-Based Framework to Capture Vocabulary Quality in NLP',
 'Towards Linguistically Generalizable NLP Systems: A Workshop and Shared Task',
 'Wikimedia data for AI: a review of Wikimedia datasets for NLP tasks and AI-assisted editing',
 'From Code-Centric to Concept-Centric: Teaching NLP with LLM-Assisted "Vibe Coding"',
 'Solving the Right Problem is Key for Translational NLP: A Case Study in UMLS Vocabulary Insertion',
 'NLP-assisted software testing: A systematic mapping of the literature',
 'News Signals: An NLP Library for Text and Time Series',
 'Augmenting NLP data to counter Annotation Artifacts for NLI Tasks',
 'What is SemEval evaluating? A Systematic Analysis of Evaluation Campaigns in NLP',
 'Dealing with Data for RE: Mitigating Challenges while using NLP and Generative AI',
 'Applied Language Technology: NLP for the Humanities',
 'Explaining Predictions of Non-Linear Classifiers in NLP',
 'Gradual Fine-Tuning for Low-Resource Domain Adaptation',
 "Complete Complementary Results Report of the MARF's NLP Approach to the DEFT 2010 Competition",
 'Missing Information, Unresponsive Authors, Experimental Flaws: The Impossibility of Assessing the Reproducibility of Previous Human Evaluations in NLP',
 'Neural Unsupervised Domain Adaptation in NLP---A Survey',
 'Evolution of ESG-focused DLT Research: An NLP Analysis of the Literature',
 'Aviation Safety Enhancement via NLP & Deep Learning: Classifying Flight Phases in ATSB Safety Reports',
 'Faithfulness and the Notion of Adversarial Sensitivity in NLP Explanations',
 'Searching for a Search Method: Benchmarking Search Algorithms for Generating NLP Adversarial Examples',
 'Towards Open-Ended Discovery for Low-Resource NLP',
 'Setting Standards in Turkish NLP: TR-MMLU for Large Language Model Evaluation',
 'Aspect-based Sentiment Evaluation of Chess Moves (ASSESS): an NLP-based Method for Evaluating Chess Strategies from Textbooks',
 'Parsing Thai Social Data: A New Challenge for Thai NLP',
 'Does it care what you asked? Understanding Importance of Verbs in Deep Learning QA System',
 'Annotation Imputation to Individualize Predictions: Initial Studies on Distribution Dynamics and Model Predictions',
 'Advancing Uto-Aztecan Language Technologies: A Case Study on the Endangered Comanche Language',
 'The Nature of NLP: Analyzing Contributions in NLP Papers',
 'Explainable Identification of Hate Speech towards Islam using Graph Neural Networks',
 'TajPersLexon: A Tajik-Persian Lexical Resource and Hybrid Model for Cross-Script Low-Resource NLP',
 'NLP Security and Ethics, in the Wild',
 'The NLP Engine: A Universal Turing Machine for NLP',
 'torchdistill Meets Hugging Face Libraries for Reproducible, Coding-Free Deep Learning Studies: A Case Study on NLP',
 'NLP for Ghanaian Languages',
 'The Current State of Finnish NLP',
 'Preregistering NLP Research',
 'State of NLP in Kenya: A Survey',
 'A Survey of Race, Racism, and Anti-Racism in NLP',
 'An NLP Assistant for Clide',
 'The Law and NLP: Bridging Disciplinary Disconnects',
 'CogErgLLM: Exploring Large Language Model Systems Design Perspective Using Cognitive Ergonomics',
 'STAMP 4 NLP -- An Agile Framework for Rapid Quality-Driven NLP Applications Development',
 'Foundations and Evaluations in NLP',
 "NLP needs Diversity outside of 'Diversity'",
 'The Radiation Oncology NLP Database',
 'The NLP Sandbox: an efficient model-to-data system to enable federated and unbiased evaluation of clinical NLP models',
 'Switching Contexts: Transportability Measures for NLP',
 'A Material Lens on Coloniality in NLP',
 'Towards Climate Awareness in NLP Research',
 "Grounding 'Grounding' in NLP",
 'Spark NLP: Natural Language Understanding at Scale',
 'NLP Privacy Risk Identification in Social Media (NLP-PRISM): A Survey',
 'A Data-Centric Framework for Composable NLP Workflows',
 'Visualizing NLP annotations for Crowdsourcing',
 'An Audit on the Perspectives and Challenges of Hallucinations in NLP',
 'TextAttack: Lessons learned in designing Python frameworks for NLP',
 'Large Language Models Meet NLP: A Survey',
 'A Survey of Data Augmentation Approaches for NLP',
 'NLP Sampling: Combining MCMC and NLP Methods for Diverse Constrained Sampling',
 'NLP and CALL: integration is working',
 'On the Origins of Bias in NLP through the Lens of the Jim Code',
 'Low-Resource Adaptation of Neural NLP Models',
 'Distributed NLP',
 'From Insights to Actions: The Impact of Interpretability and Analysis Research on NLP',
 'NLPStatTest: A Toolkit for Comparing NLP System Performance',
 'NusaCrowd: A Call for Open and Reproducible NLP Research in Indonesian Languages',
 'Towards Improving Adversarial Training of NLP Models',
 'NLP for Knowledge Discovery and Information Extraction from Energetics Corpora',
 'Challenges and Strategies in Cross-Cultural NLP',
 'The Future of NLP may not be at NLP Conferences: Scholarly Migration Patterns in Natural Language Processing',
 'A Taxonomy of Ambiguity Types for NLP',
 'Measure and Improve Robustness in NLP Models: A Survey',
 'Energy and Policy Considerations for Deep Learning in NLP',
 'Leveraging AI and NLP for Bank Marketing: A Systematic Review and Gap Analysis',
 'autoNLP: NLP Feature Recommendations for Text Analytics Applications',
 'NLP for The Greek Language: A Longer Survey',
 'Countering Online Hate Speech: An NLP Perspective',
 'Taxonomic survey of Hindi Language NLP systems',
 'Re-contextualizing Fairness in NLP: The Case of India',
 'A Survey of Adversarial Defences and Robustness in NLP',
 'VNLP: Turkish NLP Package',
 'Notes on Deep Learning for NLP',
 'Reproducibility Beyond the Research Community: Experience from NLP Beginners',
 'Distillation-Resistant Watermarking for Model Protection in NLP',
 'Representing Numbers in NLP: a Survey and a Vision']

In [26]:
articles = []

In [27]:
for article in entries :
    title = article.find("{http://www.w3.org/2005/Atom}title")
    article_data = {"title" : title.text}
    articles.append(article_data)

In [28]:
articles

[{'title': 'A dissemination workshop for introducing young Italian students to NLP'},
 {'title': 'Teaching NLP with Bracelets and Restaurant Menus: An Interactive Workshop for Italian Students'},
 {'title': 'GR-NLP-TOOLKIT: An Open-Source NLP Toolkit for Modern Greek'},
 {'title': 'How Good Is NLP? A Sober Look at NLP Tasks through the Lens of Social Impact'},
 {'title': 'NLP-ADBench: NLP Anomaly Detection Benchmark'},
 {'title': 'Teaching NLP outside Linguistics and Computer Science classrooms: Some challenges and some opportunities'},
 {'title': 'A Survey on Recognizing Textual Entailment as an NLP Evaluation'},
 {'title': 'Training an NLP Scholar at a Small Liberal Arts College: A Backwards Designed Course Proposal'},
 {'title': 'Characterizing the Efficiency vs. Accuracy Trade-off for Long-Context NLP Models'},
 {'title': 'Methods for the Design and Evaluation of HCI+NLP Systems'},
 {'title': 'Natural Language Processing 4 All (NLP4All): A New Online Platform for Teaching and Learning NLP Concepts'},
 {'title': 'Transformers: "The End of History" for NLP?'},
 {'title': 'Defining a New NLP Playground'},
 {'title': 'TurkicNLP: An NLP Toolkit for Turkic Languages'},
 {'title': 'A Survey on Patent Analysis: From NLP to Multimodal AI'},
 {'title': 'Autoencoder-Based Framework to Capture Vocabulary Quality in NLP'},
 {'title': 'Towards Linguistically Generalizable NLP Systems: A Workshop and Shared Task'},
 {'title': 'Wikimedia data for AI: a review of Wikimedia datasets for NLP tasks and AI-assisted editing'},
 {'title': 'From Code-Centric to Concept-Centric: Teaching NLP with LLM-Assisted "Vibe Coding"'},
 {'title': 'Solving the Right Problem is Key for Translational NLP: A Case Study in UMLS Vocabulary Insertion'},
 {'title': 'NLP-assisted software testing: A systematic mapping of the literature'},
 {'title': 'News Signals: An NLP Library for Text and Time Series'},
 {'title': 'Augmenting NLP data to counter Annotation Artifacts for NLI Tasks'},
 {'title': 'What is SemEval evaluating? A Systematic Analysis of Evaluation Campaigns in NLP'},
 {'title': 'Dealing with Data for RE: Mitigating Challenges while using NLP and Generative AI'},
 {'title': 'Applied Language Technology: NLP for the Humanities'},
 {'title': 'Explaining Predictions of Non-Linear Classifiers in NLP'},
 {'title': 'Gradual Fine-Tuning for Low-Resource Domain Adaptation'},
 {'title': "Complete Complementary Results Report of the MARF's NLP Approach to the DEFT 2010 Competition"},
 {'title': 'Missing Information, Unresponsive Authors, Experimental Flaws: The Impossibility of Assessing the Reproducibility of Previous Human Evaluations in NLP'},
 {'title': 'Neural Unsupervised Domain Adaptation in NLP---A Survey'},
 {'title': 'Evolution of ESG-focused DLT Research: An NLP Analysis of the Literature'},
 {'title': 'Aviation Safety Enhancement via NLP & Deep Learning: Classifying Flight Phases in ATSB Safety Reports'},
 {'title': 'Faithfulness and the Notion of Adversarial Sensitivity in NLP Explanations'},
 {'title': 'Searching for a Search Method: Benchmarking Search Algorithms for Generating NLP Adversarial Examples'},
 {'title': 'Towards Open-Ended Discovery for Low-Resource NLP'},
 {'title': 'Setting Standards in Turkish NLP: TR-MMLU for Large Language Model Evaluation'},
 {'title': 'Aspect-based Sentiment Evaluation of Chess Moves (ASSESS): an NLP-based Method for Evaluating Chess Strategies from Textbooks'},
 {'title': 'Parsing Thai Social Data: A New Challenge for Thai NLP'},
 {'title': 'Does it care what you asked? Understanding Importance of Verbs in Deep Learning QA System'},
 {'title': 'Annotation Imputation to Individualize Predictions: Initial Studies on Distribution Dynamics and Model Predictions'},
 {'title': 'Advancing Uto-Aztecan Language Technologies: A Case Study on the Endangered Comanche Language'},
 {'title': 'The Nature of NLP: Analyzing Contributions in NLP Papers'},
 {'title': 'Explainable Identification of Hate Speech towards Islam using Graph Neural Networks'},
 {'title': 'TajPersLexon: A Tajik-Persian Lexical Resource and Hybrid Model for Cross-Script Low-Resource NLP'},
 {'title': 'NLP Security and Ethics, in the Wild'},
 {'title': 'The NLP Engine: A Universal Turing Machine for NLP'},
 {'title': 'torchdistill Meets Hugging Face Libraries for Reproducible, Coding-Free Deep Learning Studies: A Case Study on NLP'},
 {'title': 'NLP for Ghanaian Languages'},
 {'title': 'The Current State of Finnish NLP'},
 {'title': 'Preregistering NLP Research'},
 {'title': 'State of NLP in Kenya: A Survey'},
 {'title': 'A Survey of Race, Racism, and Anti-Racism in NLP'},
 {'title': 'An NLP Assistant for Clide'},
 {'title': 'The Law and NLP: Bridging Disciplinary Disconnects'},
 {'title': 'CogErgLLM: Exploring Large Language Model Systems Design Perspective Using Cognitive Ergonomics'},
 {'title': 'STAMP 4 NLP -- An Agile Framework for Rapid Quality-Driven NLP Applications Development'},
 {'title': 'Foundations and Evaluations in NLP'},
 {'title': "NLP needs Diversity outside of 'Diversity'"},
 {'title': 'The Radiation Oncology NLP Database'},
 {'title': 'The NLP Sandbox: an efficient model-to-data system to enable federated and unbiased evaluation of clinical NLP models'},
 {'title': 'Switching Contexts: Transportability Measures for NLP'},
 {'title': 'A Material Lens on Coloniality in NLP'},
 {'title': 'Towards Climate Awareness in NLP Research'},
 {'title': "Grounding 'Grounding' in NLP"},
 {'title': 'Spark NLP: Natural Language Understanding at Scale'},
 {'title': 'NLP Privacy Risk Identification in Social Media (NLP-PRISM): A Survey'},
 {'title': 'A Data-Centric Framework for Composable NLP Workflows'},
 {'title': 'Visualizing NLP annotations for Crowdsourcing'},
 {'title': 'An Audit on the Perspectives and Challenges of Hallucinations in NLP'},
 {'title': 'TextAttack: Lessons learned in designing Python frameworks for NLP'},
 {'title': 'Large Language Models Meet NLP: A Survey'},
 {'title': 'A Survey of Data Augmentation Approaches for NLP'},
 {'title': 'NLP Sampling: Combining MCMC and NLP Methods for Diverse Constrained Sampling'},
 {'title': 'NLP and CALL: integration is working'},
 {'title': 'On the Origins of Bias in NLP through the Lens of the Jim Code'},
 {'title': 'Low-Resource Adaptation of Neural NLP Models'},
 {'title': 'Distributed NLP'},
 {'title': 'From Insights to Actions: The Impact of Interpretability and Analysis Research on NLP'},
 {'title': 'NLPStatTest: A Toolkit for Comparing NLP System Performance'},
 {'title': 'NusaCrowd: A Call for Open and Reproducible NLP Research in Indonesian Languages'},
 {'title': 'Towards Improving Adversarial Training of NLP Models'},
 {'title': 'NLP for Knowledge Discovery and Information Extraction from Energetics Corpora'},
 {'title': 'Challenges and Strategies in Cross-Cultural NLP'},
 {'title': 'The Future of NLP may not be at NLP Conferences: Scholarly Migration Patterns in Natural Language Processing'},
 {'title': 'A Taxonomy of Ambiguity Types for NLP'},
 {'title': 'Measure and Improve Robustness in NLP Models: A Survey'},
 {'title': 'Energy and Policy Considerations for Deep Learning in NLP'},
 {'title': 'Leveraging AI and NLP for Bank Marketing: A Systematic Review and Gap Analysis'},
 {'title': 'autoNLP: NLP Feature Recommendations for Text Analytics Applications'},
 {'title': 'NLP for The Greek Language: A Longer Survey'},
 {'title': 'Countering Online Hate Speech: An NLP Perspective'},
 {'title': 'Taxonomic survey of Hindi Language NLP systems'},
 {'title': 'Re-contextualizing Fairness in NLP: The Case of India'},
 {'title': 'A Survey of Adversarial Defences and Robustness in NLP'},
 {'title': 'VNLP: Turkish NLP Package'},
 {'title': 'Notes on Deep Learning for NLP'},
 {'title': 'Reproducibility Beyond the Research Community: Experience from NLP Beginners'},
 {'title': 'Distillation-Resistant Watermarking for Model Protection in NLP'},
 {'title': 'Representing Numbers in NLP: a Survey and a Vision'}]

In [29]:
articles=[]

In [30]:
for article in entries :
    title = article.find("{http://www.w3.org/2005/Atom}title")
    summary = article.find("{http://www.w3.org/2005/Atom}summary")
    link = article.find("{http://www.w3.org/2005/Atom}id")
    published = article.find("{http://www.w3.org/2005/Atom}published")
    article_data = {"title":title.text , "summary":summary.text , "link":link.text , "published":published.text }
    articles.append(article_data)

In [31]:
articles

[{'title': 'A dissemination workshop for introducing young Italian students to NLP',
  'summary': 'We describe and make available the game-based material developed for a laboratory run at several Italian science festivals to popularize NLP among young students.',
  'link': 'http://arxiv.org/abs/2104.12405v2',
  'published': '2021-04-26T09:00:56Z'},
 {'title': 'Teaching NLP with Bracelets and Restaurant Menus: An Interactive Workshop for Italian Students',
  'summary': 'Although Natural Language Processing (NLP) is at the core of many tools young people use in their everyday life, high school curricula (in Italy) do not include any computational linguistics education. This lack of exposure makes the use of such tools less responsible than it could be and makes choosing computational linguistics as a university degree unlikely. To raise awareness, curiosity, and longer-term interest in young people, we have developed an interactive workshop designed to illustrate the basic principles of NLP and computational linguistics to high school Italian students aged between 13 and 18 years. The workshop takes the form of a game in which participants play the role of machines needing to solve some of the most common problems a computer faces in understanding language: from voice recognition to Markov chains to syntactic parsing. Participants are guided through the workshop with the help of instructors, who present the activities and explain core concepts from computational linguistics. The workshop was presented at numerous outlets in Italy between 2019 and 2021, both face-to-face and online.',
  'link': 'http://arxiv.org/abs/2104.12422v2',
  'published': '2021-04-26T09:23:52Z'},
 {'title': 'GR-NLP-TOOLKIT: An Open-Source NLP Toolkit for Modern Greek',
  'summary': 'We present GR-NLP-TOOLKIT, an open-source natural language processing (NLP) toolkit developed specifically for modern Greek. The toolkit provides state-of-the-art performance in five core NLP tasks, namely part-of-speech tagging, morphological tagging, dependency parsing, named entity recognition, and Greeklishto-Greek transliteration. The toolkit is based on pre-trained Transformers, it is freely available, and can be easily installed in Python (pip install gr-nlp-toolkit). It is also accessible through a demonstration platform on HuggingFace, along with a publicly available API for non-commercial use. We discuss the functionality provided for each task, the underlying methods, experiments against comparable open-source toolkits, and future possible enhancements. The toolkit is available at: https://github.com/nlpaueb/gr-nlp-toolkit',
  'link': 'http://arxiv.org/abs/2412.08520v1',
  'published': '2024-12-11T16:34:23Z'},
 {'title': 'How Good Is NLP? A Sober Look at NLP Tasks through the Lens of Social Impact',
  'summary': 'Recent years have seen many breakthroughs in natural language processing (NLP), transitioning it from a mostly theoretical field to one with many real-world applications. Noting the rising number of applications of other machine learning and AI techniques with pervasive societal impact, we anticipate the rising importance of developing NLP technologies for social good. Inspired by theories in moral philosophy and global priorities research, we aim to promote a guideline for social good in the context of NLP. We lay the foundations via the moral philosophy definition of social good, propose a framework to evaluate the direct and indirect real-world impact of NLP tasks, and adopt the methodology of global priorities research to identify priority causes for NLP research. Finally, we use our theoretical framework to provide some practical guidelines for future NLP research for social good. Our data and code are available at http://github.com/zhijing-jin/nlp4sg_acl2021. In addition, we curate a list of papers and resources on NLP for social good at https://github.com/zhijing-jin/NLP4SocialGood_Papers.',
  'link': 'http://arxiv.org/abs/2106.02359v3',
  'published': '2021-06-04T09:17:15Z'},
 {'title': 'NLP-ADBench: NLP Anomaly Detection Benchmark',
  'summary': 'Anomaly detection (AD) is an important machine learning task with applications in fraud detection, content moderation, and user behavior analysis. However, AD is relatively understudied in a natural language processing (NLP) context, limiting its effectiveness in detecting harmful content, phishing attempts, and spam reviews. We introduce NLP-ADBench, the most comprehensive NLP anomaly detection (NLP-AD) benchmark to date, which includes eight curated datasets and 19 state-of-the-art algorithms. These span 3 end-to-end methods and 16 two-step approaches that adapt classical, non-AD methods to language embeddings from BERT and OpenAI. Our empirical results show that no single model dominates across all datasets, indicating a need for automated model selection. Moreover, two-step methods with transformer-based embeddings consistently outperform specialized end-to-end approaches, with OpenAI embeddings outperforming those of BERT. We release NLP-ADBench at https://github.com/USC-FORTIS/NLP-ADBench, providing a unified framework for NLP-AD and supporting future investigations.',
  'link': 'http://arxiv.org/abs/2412.04784v2',
  'published': '2024-12-06T05:30:41Z'},
 {'title': 'Teaching NLP outside Linguistics and Computer Science classrooms: Some challenges and some opportunities',
  'summary': "NLP's sphere of influence went much beyond computer science research and the development of software applications in the past decade. We see people using NLP methods in a range of academic disciplines from Asian Studies to Clinical Oncology. We also notice the presence of NLP as a module in most of the data science curricula within and outside of regular university setups. These courses are taken by students from very diverse backgrounds. This paper takes a closer look at some issues related to teaching NLP to these diverse audiences based on my classroom experiences, and identifies some challenges the instructors face, particularly when there is no ecosystem of related courses for the students. In this process, it also identifies a few challenge areas for both NLP researchers and tool developers.",
  'link': 'http://arxiv.org/abs/2105.00895v1',
  'published': '2021-05-03T14:30:32Z'},
 {'title': 'A Survey on Recognizing Textual Entailment as an NLP Evaluation',
  'summary': 'Recognizing Textual Entailment (RTE) was proposed as a unified evaluation framework to compare semantic understanding of different NLP systems. In this survey paper, we provide an overview of different approaches for evaluating and understanding the reasoning capabilities of NLP systems. We then focus our discussion on RTE by highlighting prominent RTE datasets as well as advances in RTE dataset that focus on specific linguistic phenomena that can be used to evaluate NLP systems on a fine-grained level. We conclude by arguing that when evaluating NLP systems, the community should utilize newly introduced RTE datasets that focus on specific linguistic phenomena.',
  'link': 'http://arxiv.org/abs/2010.03061v1',
  'published': '2020-10-06T22:23:00Z'},
 {'title': 'Training an NLP Scholar at a Small Liberal Arts College: A Backwards Designed Course Proposal',
  'summary': 'The rapid growth in natural language processing (NLP) over the last couple years has generated student interest and excitement in learning more about the field. In this paper, we present two types of students that NLP courses might want to train. First, an "NLP engineer" who is able to flexibly design, build and apply new technologies in NLP for a wide range of tasks. Second, an "NLP scholar" who is able to pose, refine and answer questions in NLP and how it relates to the society, while also learning to effectively communicate these answers to a broader audience. While these two types of skills are not mutually exclusive -- NLP engineers should be able to think critically, and NLP scholars should be able to build systems -- we think that courses can differ in the balance of these skills. As educators at Small Liberal Arts Colleges, the strengths of our students and our institution favors an approach that is better suited to train NLP scholars. In this paper we articulate what kinds of skills an NLP scholar should have, and then adopt a backwards design to propose course components that can aid the acquisition of these skills.',
  'link': 'http://arxiv.org/abs/2408.05664v1',
  'published': '2024-08-11T00:50:59Z'},
 {'title': 'Characterizing the Efficiency vs. Accuracy Trade-off for Long-Context NLP Models',
  'summary': 'With many real-world applications of Natural Language Processing (NLP) comprising of long texts, there has been a rise in NLP benchmarks that measure the accuracy of models that can handle longer input sequences. However, these benchmarks do not consider the trade-offs between accuracy, speed, and power consumption as input sizes or model sizes are varied. In this work, we perform a systematic study of this accuracy vs. efficiency trade-off on two widely used long-sequence models - Longformer-Encoder-Decoder (LED) and Big Bird - during fine-tuning and inference on four datasets from the SCROLLS benchmark. To study how this trade-off differs across hyperparameter settings, we compare the models across four sequence lengths (1024, 2048, 3072, 4096) and two model sizes (base and large) under a fixed resource budget. We find that LED consistently achieves better accuracy at lower energy costs than Big Bird. For summarization, we find that increasing model size is more energy efficient than increasing sequence length for higher accuracy. However, this comes at the cost of a large drop in inference speed. For question answering, we find that smaller models are both more efficient and more accurate due to the larger training batch sizes possible under a fixed resource budget.',
  'link': 'http://arxiv.org/abs/2204.07288v1',
  'published': '2022-04-15T01:52:45Z'},
 {'title': 'Methods for the Design and Evaluation of HCI+NLP Systems',
  'summary': 'HCI and NLP traditionally focus on different evaluation methods. While HCI involves a small number of people directly and deeply, NLP traditionally relies on standardized benchmark evaluations that involve a larger number of people indirectly. We present five methodological proposals at the intersection of HCI and NLP and situate them in the context of ML-based NLP models. Our goal is to foster interdisciplinary collaboration and progress in both fields by emphasizing what the fields can learn from each other.',
  'link': 'http://arxiv.org/abs/2102.13461v1',
  'published': '2021-02-26T13:37:10Z'},
 {'title': 'Natural Language Processing 4 All (NLP4All): A New Online Platform for Teaching and Learning NLP Concepts',
  'summary': 'Natural Language Processing offers new insights into language data across almost all disciplines and domains, and allows us to corroborate and/or challenge existing knowledge. The primary hurdles to widening participation in and use of these new research tools are, first, a lack of coding skills in students across K-16, and in the population at large, and second, a lack of knowledge of how NLP-methods can be used to answer questions of disciplinary interest outside of linguistics and/or computer science. To broaden participation in NLP and improve NLP-literacy, we introduced a new tool web-based tool called Natural Language Processing 4 All (NLP4All). The intended purpose of NLP4All is to help teachers facilitate learning with and about NLP, by providing easy-to-use interfaces to NLP-methods, data, and analyses, making it possible for non- and novice-programmers to learn NLP concepts interactively.',
  'link': 'http://arxiv.org/abs/2105.13704v1',
  'published': '2021-05-28T09:57:22Z'},
 {'title': 'Transformers: "The End of History" for NLP?',
  'summary': 'Recent advances in neural architectures, such as the Transformer, coupled with the emergence of large-scale pre-trained models such as BERT, have revolutionized the field of Natural Language Processing (NLP), pushing the state of the art for a number of NLP tasks. A rich family of variations of these models has been proposed, such as RoBERTa, ALBERT, and XLNet, but fundamentally, they all remain limited in their ability to model certain kinds of information, and they cannot cope with certain information sources, which was easy for pre-existing models. Thus, here we aim to shed light on some important theoretical limitations of pre-trained BERT-style models that are inherent in the general Transformer architecture. First, we demonstrate in practice on two general types of tasks -- segmentation and segment labeling -- and on four datasets that these limitations are indeed harmful and that addressing them, even in some very simple and naive ways, can yield sizable improvements over vanilla RoBERTa and XLNet models. Then, we offer a more general discussion on desiderata for future additions to the Transformer architecture that would increase its expressiveness, which we hope could help in the design of the next generation of deep NLP architectures.',
  'link': 'http://arxiv.org/abs/2105.00813v2',
  'published': '2021-04-09T08:29:42Z'},
 {'title': 'Defining a New NLP Playground',
  'summary': "The recent explosion of performance of large language models (LLMs) has changed the field of Natural Language Processing (NLP) more abruptly and seismically than any other shift in the field's 80-year history. This has resulted in concerns that the field will become homogenized and resource-intensive. The new status quo has put many academic researchers, especially PhD students, at a disadvantage. This paper aims to define a new NLP playground by proposing 20+ PhD-dissertation-worthy research directions, covering theoretical analysis, new and challenging problems, learning paradigms, and interdisciplinary applications.",
  'link': 'http://arxiv.org/abs/2310.20633v1',
  'published': '2023-10-31T17:02:33Z'},
 {'title': 'TurkicNLP: An NLP Toolkit for Turkic Languages',
  'summary': 'Natural language processing for the Turkic language family, spoken by over 200 million people across Eurasia, remains fragmented, with most languages lacking unified tooling and resources. We present TurkicNLP, an open-source Python library providing a single, consistent NLP pipeline for Turkic languages across four script families: Latin, Cyrillic, Perso-Arabic, and Old Turkic Runic. The library covers tokenization, morphological analysis, part-of-speech tagging, dependency parsing, named entity recognition, bidirectional script transliteration, cross-lingual sentence embeddings, and machine translation through one language-agnostic API. A modular multi-backend architecture integrates rule-based finite-state transducers and neural models transparently, with automatic script detection and routing between script variants. Outputs follow the CoNLL-U standard for full interoperability and extension. Code and documentation are hosted at https://github.com/turkic-nlp/turkicnlp .',
  'link': 'http://arxiv.org/abs/2602.19174v5',
  'published': '2026-02-22T13:08:21Z'},
 {'title': 'A Survey on Patent Analysis: From NLP to Multimodal AI',
  'summary': 'Recent advances in Pretrained Language Models (PLMs) and Large Language Models (LLMs) have demonstrated transformative capabilities across diverse domains. The field of patent analysis and innovation is not an exception, where natural language processing (NLP) techniques presents opportunities to streamline and enhance important tasks -- such as patent classification and patent retrieval -- in the patent cycle. This not only accelerates the efficiency of patent researchers and applicants, but also opens new avenues for technological innovation and discovery. Our survey provides a comprehensive summary of recent NLP-based methods -- including multimodal ones -- in patent analysis. We also introduce a novel taxonomy for categorization based on tasks in the patent life cycle, as well as the specifics of the methods. This interdisciplinary survey aims to serve as a comprehensive resource for researchers and practitioners who work at the intersection of NLP, Multimodal AI, and patent analysis, as well as patent offices to build efficient patent systems.',
  'link': 'http://arxiv.org/abs/2404.08668v3',
  'published': '2024-04-02T20:44:06Z'},
 {'title': 'Autoencoder-Based Framework to Capture Vocabulary Quality in NLP',
  'summary': 'Linguistic richness is essential for advancing natural language processing (NLP), as dataset characteristics often directly influence model performance. However, traditional metrics such as Type-Token Ratio (TTR), Vocabulary Diversity (VOCD), and Measure of Lexical Text Diversity (MTLD) do not adequately capture contextual relationships, semantic richness, and structural complexity. In this paper, we introduce an autoencoder-based framework that uses neural network capacity as a proxy for vocabulary richness, diversity, and complexity, enabling a dynamic assessment of the interplay between vocabulary size, sentence structure, and contextual depth. We validate our approach on two distinct datasets: the DIFrauD dataset, which spans multiple domains of deceptive and fraudulent text, and the Project Gutenberg dataset, representing diverse languages, genres, and historical periods. Experimental results highlight the robustness and adaptability of our method, offering practical guidance for dataset curation and NLP model design. By enhancing traditional vocabulary evaluation, our work fosters the development of more context-aware, linguistically adaptive NLP systems.',
  'link': 'http://arxiv.org/abs/2503.00209v1',
  'published': '2025-02-28T21:45:28Z'},
 {'title': 'Towards Linguistically Generalizable NLP Systems: A Workshop and Shared Task',
  'summary': 'This paper presents a summary of the first Workshop on Building Linguistically Generalizable Natural Language Processing Systems, and the associated Build It Break It, The Language Edition shared task. The goal of this workshop was to bring together researchers in NLP and linguistics with a shared task aimed at testing the generalizability of NLP systems beyond the distributions of their training data. We describe the motivation, setup, and participation of the shared task, provide discussion of some highlighted results, and discuss lessons learned.',
  'link': 'http://arxiv.org/abs/1711.01505v1',
  'published': '2017-11-04T22:46:54Z'},
 {'title': 'Wikimedia data for AI: a review of Wikimedia datasets for NLP tasks and AI-assisted editing',
  'summary': 'Wikimedia content is used extensively by the AI community and within the language modeling community in particular. In this paper, we provide a review of the different ways in which Wikimedia data is curated to use in NLP tasks across pre-training, post-training, and model evaluations. We point to opportunities for greater use of Wikimedia content but also identify ways in which the language modeling community could better center the needs of Wikimedia editors. In particular, we call for incorporating additional sources of Wikimedia data, a greater focus on benchmarks for LLMs that encode Wikimedia principles, and greater multilingualism in Wikimedia-derived datasets.',
  'link': 'http://arxiv.org/abs/2410.08918v1',
  'published': '2024-10-11T15:46:09Z'},
 {'title': 'From Code-Centric to Concept-Centric: Teaching NLP with LLM-Assisted "Vibe Coding"',

In [32]:
import pandas as pd

In [33]:
df = pd.DataFrame(articles)

In [34]:
df

,title,summary,link,published
0,A dissemination workshop for introducing young...,We describe and make available the game-based ...,http://arxiv.org/abs/2104.12405v2,2021-04-26T09:00:56Z
1,Teaching NLP with Bracelets and Restaurant Men...,Although Natural Language Processing (NLP) is ...,http://arxiv.org/abs/2104.12422v2,2021-04-26T09:23:52Z
2,GR-NLP-TOOLKIT: An Open-Source NLP Toolkit for...,"We present GR-NLP-TOOLKIT, an open-source natu...",http://arxiv.org/abs/2412.08520v1,2024-12-11T16:34:23Z
3,How Good Is NLP? A Sober Look at NLP Tasks thr...,Recent years have seen many breakthroughs in n...,http://arxiv.org/abs/2106.02359v3,2021-06-04T09:17:15Z
4,NLP-ADBench: NLP Anomaly Detection Benchmark,Anomaly detection (AD) is an important machine...,http://arxiv.org/abs/2412.04784v2,2024-12-06T05:30:41Z
...,...,...,...,...
95,VNLP: Turkish NLP Package,"In this work, we present VNLP: the first dedic...",http://arxiv.org/abs/2403.01309v1,2024-03-02T20:46:56Z
96,Notes on Deep Learning for NLP,My notes on Deep Learning for NLP.,http://arxiv.org/abs/1808.09772v2,2018-08-29T12:58:45Z
97,Reproducibility Beyond the Research Community:...,As NLP research attracts public attention and ...,http://arxiv.org/abs/2205.02182v2,2022-05-04T16:54:00Z
98,Distillation-Resistant Watermarking for Model ...,How can we protect the intellectual property o...,http://arxiv.org/abs/2210.03312v2,2022-10-07T04:14:35Z
99,Representing Numbers in NLP: a Survey and a Vi...,NLP systems rarely give special consideration ...,http://arxiv.org/abs/2103.13136v1,2021-03-24T12:28:22Z

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      100 non-null    object
 1   summary    100 non-null    object
 2   link       100 non-null    object
 3   published  100 non-null    object
dtypes: object(4)
memory usage: 3.3+ KB

In [36]:
df.shape

(100, 4)

In [37]:
df.isnull().sum()

title        0
summary      0
link         0
published    0
dtype: int64

In [38]:
texts = df["summary"]

In [39]:
texts

0     We describe and make available the game-based ...
1     Although Natural Language Processing (NLP) is ...
2     We present GR-NLP-TOOLKIT, an open-source natu...
3     Recent years have seen many breakthroughs in n...
4     Anomaly detection (AD) is an important machine...
                            ...
95    In this work, we present VNLP: the first dedic...
96                   My notes on Deep Learning for NLP.
97    As NLP research attracts public attention and ...
98    How can we protect the intellectual property o...
99    NLP systems rarely give special consideration ...
Name: summary, Length: 100, dtype: object

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer #TfidfVectorizer is a Class

In [41]:
vectorizer = TfidfVectorizer()

In [42]:
tfidf_matrix = vectorizer.fit_transform(texts)

In [43]:
print(type(tfidf_matrix))

<class 'scipy.sparse._csr.csr_matrix'>

In [44]:
print(tfidf_matrix.shape)

(100, 2941)

In [45]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9406 stored elements and shape (100, 2941)>

In [46]:
tfidf_matrix.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.09726368, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(100, 2941))

In [47]:
feature_names = vectorizer.get_feature_names_out()

In [48]:
feature_names[:20]

array(['0905', '10', '100', '1024', '103', '11', '1100', '112', '1235',
       '13', '138', '14', '15', '16', '171', '18', '185k', '19', '192',
       '1970s'], dtype=object)

In [49]:
feature_names[80:400]

array(['90', '93', '95', '96', '98', '99', 'a2t', 'abilities', 'ability',
       'ablation', 'able', 'about', 'above', 'abroad', 'abruptly', 'absa',
       'absent', 'abstract', 'abstracts', 'abundant', 'ac', 'academia',
       'academic', 'accelerates', 'accelerating', 'accepted', 'access',
       'accessibility', 'accessible', 'accidental', 'accommodate',
       'accompanying', 'according', 'account', 'accounts', 'accumulation',
       'accuracy', 'accurate', 'achieve', 'achieved', 'achieves',
       'achieving', 'acknowledge', 'acl', 'acquisition', 'across', 'act',
       'action', 'actionable', 'active', 'activities', 'actor', 'actual',
       'actually', 'ad', 'adapt', 'adaptability', 'adaptation',
       'adapting', 'adaptive', 'adbench', 'added', 'addition',
       'additional', 'additionally', 'additions', 'address', 'addresses',
       'addressing', 'adequate', 'adequately', 'adjusting', 'adopt',
       'adopting', 'adoption', 'advance', 'advanced', 'advancement',
       'advancements', 'advances', 'advancing', 'advent', 'adversarial',
       'adversary', 'advertising', 'advocate', 'after', 'again',
       'against', 'aged', 'agenda', 'aggregation', 'agi', 'agnostic',
       'agreement', 'ai', 'aia', 'aid', 'aiding', 'aim', 'aimed',
       'aiming', 'aims', 'akin', 'alarming', 'albert', 'algorithm',
       'algorithms', 'align', 'aligned', 'alignment', 'aligns', 'all',
       'alleviate', 'alleviated', 'alleviating', 'allocation', 'allow',
       'allowing', 'allows', 'almost', 'alone', 'along', 'alongside',
       'already', 'also', 'although', 'ambiguities', 'ambiguity', 'among',
       'amount', 'amounts', 'amplified', 'an', 'analogous', 'analyses',
       'analysis', 'analytical', 'analytics', 'analyze', 'analyzes',
       'analyzing', 'ancient', 'and', 'andreligion', 'annotate',
       'annotated', 'annotating', 'annotation', 'annotations',
       'annotator', 'annotators', 'anomaly', 'anonymization', 'answer',
       'answering', 'answers', 'ant', 'anthology', 'anticipate',
       'antonyms', 'any', 'apache', 'api', 'apis', 'apparent',
       'appearing', 'appears', 'applicability', 'applicable',
       'applicants', 'application', 'applications', 'applied', 'apply',
       'approach', 'approaches', 'appropriate', 'approximate', 'arabic',
       'architecture', 'architectures', 'arduous', 'are', 'area', 'areas',
       'arguably', 'argue', 'argues', 'arguing', 'arise', 'arising',
       'around', 'arrange', 'arranged', 'array', 'arrival', 'art',
       'article', 'articles', 'articulate', 'artifacts', 'artificial',
       'arts', 'arxiv', 'as', 'asian', 'ask', 'aspect', 'aspects',
       'assembled', 'assess', 'assessed', 'assessing', 'assessment',
       'assessments', 'assist', 'assistance', 'assistant', 'assistants',
       'assisted', 'associated', 'assume', 'assurance', 'at', 'atoms',
       'atsb', 'attack', 'attacking', 'attacks', 'attempt', 'attempts',
       'attention', 'attracts', 'attribute', 'auc', 'audience',
       'audiences', 'audit', 'augmentation', 'augmented', 'australian',
       'author', 'authors', 'auto', 'autoencoder', 'automated',
       'automates', 'automatic', 'automatically', 'automating',
       'automation', 'availability', 'available', 'avenues', 'average',
       'aviation', 'avoiding', 'aware', 'awareness', 'axes', 'aztecan',
       'back', 'backend', 'background', 'backgrounds', 'backwards',
       'balance', 'bank', 'banking', 'barrier', 'barriers', 'base',
       'based', 'baseline', 'baselines', 'bases', 'basic', 'batch', 'be',
       'beam', 'became', 'because', 'become', 'becomes', 'becoming',
       'been', 'before', 'beginners', 'beginnings', 'behavior',
       'behavioral', 'behaviour', 'behind', 'being', 'benchmark',
       'benchmarking', 'benchmarks', 'beneficial', 'benefit', 'benefits',
       'bert', 'best', 'better', 'between', 'beyond', 'bias', 'biases',
       'bidirectional', 'big', 'biomedical', 'bird', 'bitcoin', 'black',
       'blockchain', 'blstm', 'blurring', 'body', 'book', 'both'],
      dtype=object)

In [50]:
#test = vectorizer.fit_transform(["i line natural language processing"])

In [51]:
#test

In [52]:
#test2 = vectorizer.get_feature_names_out()

In [53]:
#test2

In [54]:
from sklearn.metrics.pairwise import cosine_similarity #cosine_similarity is a Method

In [55]:
similarity_matrix = cosine_similarity(tfidf_matrix)

In [56]:
similarity_matrix.shape

(100, 100)

In [57]:
similarity_matrix[0]

array([1.        , 0.14606776, 0.08797942, 0.06086941, 0.03626813,
       0.11479866, 0.02035809, 0.06856561, 0.03353104, 0.04264541,
       0.08798183, 0.03457256, 0.04774593, 0.03217483, 0.03760205,
       0.03281283, 0.0661403 , 0.02392701, 0.09464061, 0.06786638,
       0.05577387, 0.06038825, 0.0357823 , 0.0343433 , 0.04594598,
       0.03377834, 0.02808725, 0.0125577 , 0.04463866, 0.03419387,
       0.03155124, 0.03089861, 0.0149425 , 0.02561934, 0.0337087 ,
       0.02578519, 0.02805123, 0.054097  , 0.03594247, 0.03184133,
       0.05645827, 0.0264687 , 0.04750421, 0.02986849, 0.01871504,
       0.04559906, 0.05290396, 0.03834511, 0.0406486 , 0.07162213,
       0.06400407, 0.05067831, 0.02548548, 0.03100542, 0.03223178,
       0.02437754, 0.04619249, 0.0446929 , 0.03230047, 0.06094008,
       0.04764596, 0.05403216, 0.03685201, 0.05278743, 0.08388446,
       0.0228912 , 0.02263735, 0.05486715, 0.04661498, 0.03205666,
       0.03012074, 0.04295679, 0.04847691, 0.05536859, 0.04566935,
       0.06446444, 0.06797631, 0.06066801, 0.04197782, 0.04178404,
       0.03754054, 0.04560306, 0.05781689, 0.03573522, 0.05439393,
       0.04788395, 0.035471  , 0.04472812, 0.03630745, 0.03626477,
       0.05439123, 0.02218624, 0.04888625, 0.03760328, 0.03923945,
       0.03930787, 0.01835589, 0.07311759, 0.03652307, 0.02955017])

In [58]:
similarity_matrix[0].argsort() [ : : -1]

array([ 0,  1,  5, 18, 10,  2, 64, 97, 49,  7, 76, 19, 16, 75, 50, 59,  3,
       77, 21, 82, 40, 20, 73, 67, 84, 90, 37, 61, 46, 63, 51, 92, 72, 85,
       12, 60, 42, 68, 56, 24, 74, 81, 45, 87, 57, 28, 71,  9, 78, 79, 48,
       95, 94, 47, 93, 14, 80, 62, 98, 88,  4, 89, 38, 22, 83, 86, 11, 23,
       29, 25, 34,  8, 15, 58, 54, 13, 69, 39, 30, 53, 31, 70, 43, 99, 26,
       36, 41, 35, 33, 52, 55, 17, 65, 66, 91,  6, 44, 96, 32, 27])

In [59]:
tops5 = similarity_matrix[0].argsort()[::-1][1:6]

In [60]:
tops5

array([ 1,  5, 18, 10,  2])

In [61]:
df.iloc[tops5]

,title,summary,link,published
1,Teaching NLP with Bracelets and Restaurant Men...,Although Natural Language Processing (NLP) is ...,http://arxiv.org/abs/2104.12422v2,2021-04-26T09:23:52Z
5,Teaching NLP outside Linguistics and Computer ...,NLP's sphere of influence went much beyond com...,http://arxiv.org/abs/2105.00895v1,2021-05-03T14:30:32Z
18,From Code-Centric to Concept-Centric: Teaching...,The rapid advancement of Large Language Models...,http://arxiv.org/abs/2602.01919v1,2026-02-02T10:21:34Z
10,Natural Language Processing 4 All (NLP4All): A...,Natural Language Processing offers new insight...,http://arxiv.org/abs/2105.13704v1,2021-05-28T09:57:22Z
2,GR-NLP-TOOLKIT: An Open-Source NLP Toolkit for...,"We present GR-NLP-TOOLKIT, an open-source natu...",http://arxiv.org/abs/2412.08520v1,2024-12-11T16:34:23Z

In [62]:
query = "academia access auc audience deep learning melika nlp"

In [63]:
query_vector = vectorizer.transform([query])

In [64]:
query_vector

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (1, 2941)>

In [65]:
query_vector.shape

(1, 2941)

In [66]:
print(len(vectorizer.get_feature_names_out()))

2941

In [67]:
print(tfidf_matrix.shape)

(100, 2941)

In [90]:
similarity = cosine_similarity(query_vector , tfidf_matrix)

In [91]:
print(similarity.shape)

(1, 100)

In [92]:
 similarity[0] # first line of query is in []

array([0.00627715, 0.00367933, 0.01092655, 0.02252542, 0.02288639,
       0.01318445, 0.01002457, 0.06746321, 0.00337555, 0.01280239,
       0.02737206, 0.02487148, 0.02179495, 0.00433807, 0.00494346,
       0.0061893 , 0.00638964, 0.0022411 , 0.02652035, 0.0062624 ,
       0.00813365, 0.00985976, 0.00283776, 0.00665612, 0.01089649,
       0.02288844, 0.00244712, 0.0206915 , 0.0044477 , 0.00778448,
       0.05551182, 0.00743702, 0.0631177 , 0.00260027, 0.00227043,
       0.01851236, 0.00303297, 0.00152034, 0.00229816, 0.0636122 ,
       0.00184583, 0.00912221, 0.014874  , 0.00394685, 0.        ,
       0.01768856, 0.01000871, 0.06969956, 0.01367069, 0.01517432,
       0.01274269, 0.01292593, 0.01486972, 0.04733046, 0.06981518,
       0.00233698, 0.02337332, 0.01066837, 0.01056004, 0.0105938 ,
       0.01497456, 0.01048407, 0.01153597, 0.01148989, 0.00794447,
       0.03133434, 0.05965451, 0.04673427, 0.04696991, 0.01010437,
       0.05375268, 0.01524515, 0.01141734, 0.00558983, 0.0358239 ,
       0.01465429, 0.04018702, 0.00511639, 0.01127738, 0.00875327,
       0.04396232, 0.03303955, 0.01218292, 0.01204234, 0.0154037 ,
       0.00739721, 0.00827374, 0.00970047, 0.01171857, 0.02275659,
       0.00722308, 0.00629689, 0.0090974 , 0.00798982, 0.0448065 ,
       0.0064077 , 0.2205868 , 0.10252148, 0.00842331, 0.00756097])

In [93]:
 sorted_indexes = similarity[0].argsort()[: : -1]

In [94]:
sorted_indexes

array([96, 97, 54, 47,  7, 39, 32, 66, 30, 70, 53, 68, 67, 94, 80, 76, 74,
       81, 65, 10, 18, 11, 56, 25,  4, 89,  3, 12, 27, 35, 45, 84, 71, 49,
       60, 42, 52, 75, 48,  5, 51,  9, 50, 82, 83, 88, 62, 63, 72, 78,  2,
       24, 57, 59, 58, 61, 69,  6, 46, 21, 87, 41, 92, 79, 98, 86, 20, 93,
       64, 29, 99, 31, 85, 90, 23, 95, 16, 91,  0, 19, 15, 73, 77, 14, 28,
       13, 43,  1,  8, 36, 22, 33, 26, 55, 38, 34, 17, 40, 37, 44])

In [95]:
top_indices =sorted_indexes [0:5]

In [96]:
df.iloc[top_indices]

,title,summary,link,published
96,Notes on Deep Learning for NLP,My notes on Deep Learning for NLP.,http://arxiv.org/abs/1808.09772v2,2018-08-29T12:58:45Z
97,Reproducibility Beyond the Research Community:...,As NLP research attracts public attention and ...,http://arxiv.org/abs/2205.02182v2,2022-05-04T16:54:00Z
54,The Law and NLP: Bridging Disciplinary Disconn...,Legal practice is intrinsically rooted in the ...,http://arxiv.org/abs/2310.14346v1,2023-10-22T16:34:31Z
47,torchdistill Meets Hugging Face Libraries for ...,Reproducibility in scientific work has been be...,http://arxiv.org/abs/2310.17644v1,2023-10-26T17:57:15Z
7,Training an NLP Scholar at a Small Liberal Art...,The rapid growth in natural language processin...,http://arxiv.org/abs/2408.05664v1,2024-08-11T00:50:59Z

In [97]:
for i in top_indices: 
    print("Title : " , df.iloc[i] ["title"])
    print("Summary : " , df.iloc[i] ["summary"])
    print("Link : " , df.iloc[i] ["link"])
    print("Published : " , df.iloc[i] ["published"])
    print("=============================================================")

Title :  Notes on Deep Learning for NLP
Summary :  My notes on Deep Learning for NLP.
Link :  http://arxiv.org/abs/1808.09772v2
Published :  2018-08-29T12:58:45Z
=============================================================
Title :  Reproducibility Beyond the Research Community: Experience from NLP Beginners
Summary :  As NLP research attracts public attention and excitement, it becomes increasingly important for it to be accessible to a broad audience. As the research community works to democratize NLP, it remains unclear whether beginners to the field can easily apply the latest developments. To understand their needs, we conducted a study with 93 students in an introductory NLP course, where students reproduced results of recent NLP papers. Surprisingly, our results suggest that their technical skill (i.e., programming experience) has limited impact on their effort spent completing the exercise. Instead, we find accessibility efforts by research authors to be key to a successful experience, including thorough documentation and easy access to required models and datasets.
Link :  http://arxiv.org/abs/2205.02182v2
Published :  2022-05-04T16:54:00Z
=============================================================
Title :  The Law and NLP: Bridging Disciplinary Disconnects
Summary :  Legal practice is intrinsically rooted in the fabric of language, yet legal practitioners and scholars have been slow to adopt tools from natural language processing (NLP). At the same time, the legal system is experiencing an access to justice crisis, which could be partially alleviated with NLP. In this position paper, we argue that the slow uptake of NLP in legal practice is exacerbated by a disconnect between the needs of the legal community and the focus of NLP researchers. In a review of recent trends in the legal NLP literature, we find limited overlap between the legal NLP community and legal academia. Our interpretation is that some of the most popular legal NLP tasks fail to address the needs of legal practitioners. We discuss examples of legal NLP tasks that promise to bridge disciplinary disconnects and highlight interesting areas for legal NLP research that remain underexplored.
Link :  http://arxiv.org/abs/2310.14346v1
Published :  2023-10-22T16:34:31Z
=============================================================
Title :  torchdistill Meets Hugging Face Libraries for Reproducible, Coding-Free Deep Learning Studies: A Case Study on NLP
Summary :  Reproducibility in scientific work has been becoming increasingly important in research communities such as machine learning, natural language processing, and computer vision communities due to the rapid development of the research domains supported by recent advances in deep learning. In this work, we present a significantly upgraded version of torchdistill, a modular-driven coding-free deep learning framework significantly upgraded from the initial release, which supports only image classification and object detection tasks for reproducible knowledge distillation experiments. To demonstrate that the upgraded framework can support more tasks with third-party libraries, we reproduce the GLUE benchmark results of BERT models using a script based on the upgraded torchdistill, harmonizing with various Hugging Face libraries. All the 27 fine-tuned BERT models and configurations to reproduce the results are published at Hugging Face, and the model weights have already been widely used in research communities. We also reimplement popular small-sized models and new knowledge distillation methods and perform additional experiments for computer vision tasks.
Link :  http://arxiv.org/abs/2310.17644v1
Published :  2023-10-26T17:57:15Z
=============================================================
Title :  Training an NLP Scholar at a Small Liberal Arts College: A Backwards Designed Course Proposal
Summary :  The rapid growth in natural language processing (NLP) over the last couple years has generated student interest and excitement in learning more about the field. In this paper, we present two types of students that NLP courses might want to train. First, an "NLP engineer" who is able to flexibly design, build and apply new technologies in NLP for a wide range of tasks. Second, an "NLP scholar" who is able to pose, refine and answer questions in NLP and how it relates to the society, while also learning to effectively communicate these answers to a broader audience. While these two types of skills are not mutually exclusive -- NLP engineers should be able to think critically, and NLP scholars should be able to build systems -- we think that courses can differ in the balance of these skills. As educators at Small Liberal Arts Colleges, the strengths of our students and our institution favors an approach that is better suited to train NLP scholars. In this paper we articulate what kinds of skills an NLP scholar should have, and then adopt a backwards design to propose course components that can aid the acquisition of these skills.
Link :  http://arxiv.org/abs/2408.05664v1
Published :  2024-08-11T00:50:59Z
=============================================================

In [104]:
for i in top_indices:
    print(similarity[0,i]) # "0" means row of query and "i" means articles from 0 to 99

0.22058680276597692
0.10252147701115125
0.06981518371510026
0.06969955830766539
0.0674632088000972

In [107]:
def recommend_articles (query):
    query_vector = vectorizer.transform([query])
    similarity = cosine_similarity(query_vector , tfidf_matrix)
    top_indexes = similarity[0].argsort()[: : -1] [0:5]
    for i in top_indices: 
        print("Title : " , df.iloc[i] ["title"])
        print("Summary : " , df.iloc[i] ["summary"])
        print("Link : " , df.iloc[i] ["link"])
        print("Published : " , df.iloc[i] ["published"])
        print("=============================================================")

In [110]:
recommend_articles("natural language processing")

Title :  Notes on Deep Learning for NLP
Summary :  My notes on Deep Learning for NLP.
Link :  http://arxiv.org/abs/1808.09772v2
Published :  2018-08-29T12:58:45Z
=============================================================
Title :  Reproducibility Beyond the Research Community: Experience from NLP Beginners
Summary :  As NLP research attracts public attention and excitement, it becomes increasingly important for it to be accessible to a broad audience. As the research community works to democratize NLP, it remains unclear whether beginners to the field can easily apply the latest developments. To understand their needs, we conducted a study with 93 students in an introductory NLP course, where students reproduced results of recent NLP papers. Surprisingly, our results suggest that their technical skill (i.e., programming experience) has limited impact on their effort spent completing the exercise. Instead, we find accessibility efforts by research authors to be key to a successful experience, including thorough documentation and easy access to required models and datasets.
Link :  http://arxiv.org/abs/2205.02182v2
Published :  2022-05-04T16:54:00Z
=============================================================
Title :  The Law and NLP: Bridging Disciplinary Disconnects
Summary :  Legal practice is intrinsically rooted in the fabric of language, yet legal practitioners and scholars have been slow to adopt tools from natural language processing (NLP). At the same time, the legal system is experiencing an access to justice crisis, which could be partially alleviated with NLP. In this position paper, we argue that the slow uptake of NLP in legal practice is exacerbated by a disconnect between the needs of the legal community and the focus of NLP researchers. In a review of recent trends in the legal NLP literature, we find limited overlap between the legal NLP community and legal academia. Our interpretation is that some of the most popular legal NLP tasks fail to address the needs of legal practitioners. We discuss examples of legal NLP tasks that promise to bridge disciplinary disconnects and highlight interesting areas for legal NLP research that remain underexplored.
Link :  http://arxiv.org/abs/2310.14346v1
Published :  2023-10-22T16:34:31Z
=============================================================
Title :  torchdistill Meets Hugging Face Libraries for Reproducible, Coding-Free Deep Learning Studies: A Case Study on NLP
Summary :  Reproducibility in scientific work has been becoming increasingly important in research communities such as machine learning, natural language processing, and computer vision communities due to the rapid development of the research domains supported by recent advances in deep learning. In this work, we present a significantly upgraded version of torchdistill, a modular-driven coding-free deep learning framework significantly upgraded from the initial release, which supports only image classification and object detection tasks for reproducible knowledge distillation experiments. To demonstrate that the upgraded framework can support more tasks with third-party libraries, we reproduce the GLUE benchmark results of BERT models using a script based on the upgraded torchdistill, harmonizing with various Hugging Face libraries. All the 27 fine-tuned BERT models and configurations to reproduce the results are published at Hugging Face, and the model weights have already been widely used in research communities. We also reimplement popular small-sized models and new knowledge distillation methods and perform additional experiments for computer vision tasks.
Link :  http://arxiv.org/abs/2310.17644v1
Published :  2023-10-26T17:57:15Z
=============================================================
Title :  Training an NLP Scholar at a Small Liberal Arts College: A Backwards Designed Course Proposal
Summary :  The rapid growth in natural language processing (NLP) over the last couple years has generated student interest and excitement in learning more about the field. In this paper, we present two types of students that NLP courses might want to train. First, an "NLP engineer" who is able to flexibly design, build and apply new technologies in NLP for a wide range of tasks. Second, an "NLP scholar" who is able to pose, refine and answer questions in NLP and how it relates to the society, while also learning to effectively communicate these answers to a broader audience. While these two types of skills are not mutually exclusive -- NLP engineers should be able to think critically, and NLP scholars should be able to build systems -- we think that courses can differ in the balance of these skills. As educators at Small Liberal Arts Colleges, the strengths of our students and our institution favors an approach that is better suited to train NLP scholars. In this paper we articulate what kinds of skills an NLP scholar should have, and then adopt a backwards design to propose course components that can aid the acquisition of these skills.
Link :  http://arxiv.org/abs/2408.05664v1
Published :  2024-08-11T00:50:59Z
=============================================================